package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.systemconfig.AssetType;
import com.hubformath.mathhubservice.model.systemconfig.PaymentMethod;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "assets")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Asset {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "asset_id")
    private String assetId;

    @ManyToOne
    @JoinColumn(name = "payment_method_id", unique = false, nullable = false)
    private PaymentMethod paymentMethod;

    @Column(name = "narration")
    private String narration;

    @ManyToOne
    @JoinColumn(name = "asset_type_id", unique = false, nullable = false)
    private AssetType assetType;

    @Column(name = "amount")
    private Double amount;

    @ManyToOne
    @JoinColumn(name = "created_by", unique = false, nullable = false)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    @SuppressWarnings("unused")
    public Asset() {
        // Required by JPA
    }

    public Asset(String narration, Double amount, PaymentMethod paymentMethod, AssetType assetType) {
        this.narration = narration;
        this.amount = amount;
        this.paymentMethod = paymentMethod;
        this.assetType = assetType;
    }

    public String getAssetId() {
        return assetId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public AssetType getAssetType() {
        return assetType;
    }

    public void setAssetType(AssetType assetType) {
        this.assetType = assetType;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Asset asset)) return false;
        return Objects.equals(getAssetId(), asset.getAssetId())
                && Objects.equals(getPaymentMethod(), asset.getPaymentMethod())
                && Objects.equals(getNarration(), asset.getNarration())
                && Objects.equals(getAssetType(), asset.getAssetType())
                && Objects.equals(getAmount(), asset.getAmount())
                && Objects.equals(getCreatedBy(), asset.getCreatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAssetId(),
                            getPaymentMethod(),
                            getNarration(),
                            getAssetType(),
                            getAmount(),
                            getCreatedBy());
    }

    @Override
    public String toString() {
        return "Asset{" +
                "assetId='" + assetId + '\'' +
                ", paymentMethod=" + paymentMethod +
                ", narration='" + narration + '\'' +
                ", assetType=" + assetType +
                ", amount=" + amount +
                ", createdBy=" + createdBy +
                '}';
    }
}
