package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.systemconfig.IncomeType;
import com.hubformath.mathhubservice.model.systemconfig.PaymentMethod;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "incomes")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Income {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @ManyToOne
    @JoinColumn(name = "payment_method_id", unique = false, nullable = false)
    private PaymentMethod paymentMethod;

    @Column(name = "narration")
    private String narration;

    @ManyToOne
    @JoinColumn(name = "income_type_id", unique = false, nullable = false)
    private IncomeType type;

    @Column(name = "amount")
    private Double amount;

    @ManyToOne
    @JoinColumn(name = "created_by", unique = false, nullable = false)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    @SuppressWarnings("unused")
    public Income() {
        // Required by JPA
    }

    public Income(PaymentMethod paymentMethod, String narration, IncomeType type, Double amount, User createdBy) {
        this.paymentMethod = paymentMethod;
        this.narration = narration;
        this.type = type;
        this.amount = amount;
        this.createdBy = createdBy;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public IncomeType getType() {
        return type;
    }

    public void setType(IncomeType type) {
        this.type = type;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Income income)) return false;
        return Objects.equals(getId(), income.getId())
                && Objects.equals(getPaymentMethod(), income.getPaymentMethod())
                && Objects.equals(getNarration(), income.getNarration())
                && Objects.equals(getType(), income.getType())
                && Objects.equals(getAmount(), income.getAmount())
                && Objects.equals(getCreatedBy(), income.getCreatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                            getPaymentMethod(),
                            getNarration(),
                            getType(),
                            getAmount(),
                            getCreatedBy());
    }

    @Override
    public String toString() {
        return "Income{" +
                "id='" + id + '\'' +
                ", paymentMethod=" + paymentMethod +
                ", narration='" + narration + '\'' +
                ", type=" + type +
                ", amount=" + amount +
                ", createdBy=" + createdBy +
                '}';
    }
}
