package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.systemconfig.IncomeType;
import com.hubformath.mathhubservice.model.systemconfig.PaymentMethod;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "incomes")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Income {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String incomeId;

    @ManyToOne
    @JoinColumn(name = "payment_method_id", unique = false, nullable = false)
    private PaymentMethod paymentMethod;

    @Column(name = "narration")
    private String narration;

    @ManyToOne
    @JoinColumn(name = "income_type_id", unique = false, nullable = false)
    private IncomeType incomeType;

    @Column(name = "amount")
    private Double amount;

    @ManyToOne
    @JoinColumn(name = "created_by", unique = false, nullable = false)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    @SuppressWarnings("unused")
    public Income() {
        // Required by JPA
    }

    public Income(PaymentMethod paymentMethod, String narration, IncomeType incomeType, Double amount, User createdBy) {
        this.paymentMethod = paymentMethod;
        this.narration = narration;
        this.incomeType = incomeType;
        this.amount = amount;
        this.createdBy = createdBy;
    }

    public String getIncomeId() {
        return incomeId;
    }

    public void setIncomeId(String incomeId) {
        this.incomeId = incomeId;
    }

    public IncomeType getIncomeType() {
        return incomeType;
    }

    public void setIncomeType(IncomeType incomeType) {
        this.incomeType = incomeType;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Income income)) return false;
        return Objects.equals(getIncomeId(), income.getIncomeId())
                && Objects.equals(getPaymentMethod(), income.getPaymentMethod())
                && Objects.equals(getNarration(), income.getNarration())
                && Objects.equals(getIncomeType(), income.getIncomeType())
                && Objects.equals(getAmount(), income.getAmount())
                && Objects.equals(getCreatedBy(), income.getCreatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIncomeId(),
                            getPaymentMethod(),
                            getNarration(),
                            getIncomeType(),
                            getAmount(),
                            getCreatedBy());
    }

    @Override
    public String toString() {
        return "Income{" +
                "incomeId=" + incomeId +
                ", paymentMethod=" + paymentMethod +
                ", narration='" + narration + '\'' +
                ", incomeType=" + incomeType +
                ", amount=" + amount +
                ", createdBy=" + createdBy +
                '}';
    }
}
