package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.sis.Student;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "invoices")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Invoice {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String invoiceId;

    @Column(name = "invoice_number")
    private String invoiceNumber;

    @ManyToOne
    @JoinColumn(name = "student_id", unique = false, nullable = false)
    private Student student;

    @Column(name = "invoice_date")
    private LocalDate invoiceDate;

    @Column(name = "amount")
    private Double amount;

    @Column(name = "narration")
    private String narration;

    @Enumerated(EnumType.STRING)
    @Column(name = "invoice_status")
    private InvoiceStatus invoiceStatus;

    @Column(name = "due_date")
    private LocalDate dueDate;

    @ManyToOne
    @JoinColumn(name = "issued_by", unique = false, nullable = false)
    private User issuedBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    public Invoice() {
    }

    public Invoice(Student student, final Double amount, final String narration, InvoiceStatus invoiceStatus, User issuedBy) {
        this.student = student;
        this.invoiceStatus = invoiceStatus;
        this.issuedBy = issuedBy;
        this.invoiceNumber = UUID.randomUUID().toString().toUpperCase().replace("-", "");
        this.invoiceDate = LocalDate.now();
        this.amount = amount;
        this.narration = narration;
        this.invoiceStatus = InvoiceStatus.PENDING;
        this.dueDate = LocalDate.now().plusDays(14);
    }

    public String getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public LocalDate getInvoiceDate() {
        return invoiceDate;
    }

    public void setInvoiceDate(LocalDate invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public User getIssuedBy() {
        return issuedBy;
    }

    public void setIssuedBy(User issuedBy) {
        this.issuedBy = issuedBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public InvoiceStatus getInvoiceStatus() {
        return invoiceStatus;
    }

    public void setInvoiceStatus(InvoiceStatus invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Invoice invoice)) return false;
        return Objects.equals(getInvoiceId(), invoice.getInvoiceId())
                && Objects.equals(getInvoiceNumber(), invoice.getInvoiceNumber())
                && Objects.equals(getInvoiceDate(), invoice.getInvoiceDate())
                && Objects.equals(getAmount(), invoice.getAmount())
                && Objects.equals(getNarration(), invoice.getNarration())
                && getInvoiceStatus() == invoice.getInvoiceStatus()
                && Objects.equals(getDueDate(), invoice.getDueDate())
                && Objects.equals(getIssuedBy(), invoice.getIssuedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getInvoiceId(),
                            getInvoiceNumber(),
                            getInvoiceDate(),
                            getAmount(),
                            getNarration(),
                            getInvoiceStatus(),
                            getDueDate(),
                            getIssuedBy());
    }

    @Override
    public String toString() {
        return "Invoice{" +
                "invoiceId=" + invoiceId +
                ", invoiceNumber='" + invoiceNumber + '\'' +
                ", student=" + student +
                ", invoiceDate=" + invoiceDate +
                ", amount=" + amount +
                ", narration='" + narration + '\'' +
                ", invoiceStatus=" + invoiceStatus +
                ", dueDate=" + dueDate +
                ", issuedBy=" + issuedBy +
                '}';
    }
}
