package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.sis.Student;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
@Table(name = "invoices")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Invoice {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(name = "invoice_number")
    private String number;

    @ManyToOne
    @JoinColumn(name = "student_id", unique = false, nullable = false)
    private Student student;

    @Column(name = "invoice_date")
    private LocalDate dateGenerated;

    @Column(name = "amount")
    private Double amount;

    @Column(name = "narration")
    private String narration;

    @Enumerated(EnumType.STRING)
    @Column(name = "invoice_status")
    private InvoiceStatus status;

    @Column(name = "due_date")
    private LocalDate dueDate;

    @ManyToOne
    @JoinColumn(name = "issued_by", unique = false, nullable = false)
    private User issuedBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    public Invoice() {
    }

    public Invoice(Student student, final Double amount, final String narration, InvoiceStatus status, User issuedBy) {
        this.student = student;
        this.status = status;
        this.issuedBy = issuedBy;
        this.number = UUID.randomUUID().toString().toUpperCase().replace("-", "");
        this.dateGenerated = LocalDate.now();
        this.amount = amount;
        this.narration = narration;
        this.status = InvoiceStatus.PENDING;
        this.dueDate = LocalDate.now().plusDays(14);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public LocalDate getDateGenerated() {
        return dateGenerated;
    }

    public void setDateGenerated(LocalDate dateGenerated) {
        this.dateGenerated = dateGenerated;
    }

    public User getIssuedBy() {
        return issuedBy;
    }

    public void setIssuedBy(User issuedBy) {
        this.issuedBy = issuedBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public InvoiceStatus getStatus() {
        return status;
    }

    public void setStatus(InvoiceStatus status) {
        this.status = status;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Invoice invoice)) return false;
        return Objects.equals(getId(), invoice.getId())
                && Objects.equals(getNumber(), invoice.getNumber())
                && Objects.equals(getDateGenerated(), invoice.getDateGenerated())
                && Objects.equals(getAmount(), invoice.getAmount())
                && Objects.equals(getNarration(), invoice.getNarration())
                && getStatus() == invoice.getStatus()
                && Objects.equals(getDueDate(), invoice.getDueDate())
                && Objects.equals(getIssuedBy(), invoice.getIssuedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                            getNumber(),
                            getDateGenerated(),
                            getAmount(),
                            getNarration(),
                            getStatus(),
                            getDueDate(),
                            getIssuedBy());
    }

    @Override
    public String toString() {
        return "Invoice{" +
                "id='" + id + '\'' +
                ", number='" + number + '\'' +
                ", student=" + student +
                ", dateGenerated=" + dateGenerated +
                ", amount=" + amount +
                ", narration='" + narration + '\'' +
                ", status=" + status +
                ", dueDate=" + dueDate +
                ", issuedBy=" + issuedBy +
                '}';
    }
}
