package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.systemconfig.LiabilityType;
import com.hubformath.mathhubservice.model.systemconfig.PaymentMethod;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "liabilities")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Liability {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "liability_id")
    private String liabilityId;

    @OneToOne
    @JoinColumn(name = "liability_type_id")
    private LiabilityType liabilityType;

    @ManyToOne
    @JoinColumn(name = "payment_method_id", unique = false, nullable = false)
    private PaymentMethod paymentMethod;

    @Column(name = "amount")
    private Double amount;

    @Column(name = "narration")
    private String narration;

    @ManyToOne
    @JoinColumn(name = "created_by", unique = false, nullable = false)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    public Liability() {
    }

    public Liability(LiabilityType liabilityType, PaymentMethod paymentMethod, Double amount, String narration, User createdBy) {
        this.liabilityType = liabilityType;
        this.paymentMethod = paymentMethod;
        this.amount = amount;
        this.narration = narration;
        this.createdBy = createdBy;
    }

    public String getLiabilityId() {
        return liabilityId;
    }

    public void setLiabilityId(String liabilityId) {
        this.liabilityId = liabilityId;
    }

    public LiabilityType getLiabilityType() {
        return liabilityType;
    }

    public void setLiabilityType(LiabilityType liabilityType) {
        this.liabilityType = liabilityType;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Liability liability)) return false;
        return Objects.equals(getLiabilityId(), liability.getLiabilityId())
                && Objects.equals(getLiabilityType(), liability.getLiabilityType())
                && Objects.equals(getPaymentMethod(), liability.getPaymentMethod())
                && Objects.equals(getAmount(), liability.getAmount())
                && Objects.equals(getNarration(), liability.getNarration())
                && Objects.equals(getCreatedBy(), liability.getCreatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLiabilityId(),
                            getLiabilityType(),
                            getPaymentMethod(),
                            getAmount(),
                            getNarration(),
                            getCreatedBy());
    }

    @Override
    public String toString() {
        return "Liability{" +
                "liabilityId=" + liabilityId +
                ", liabilityType=" + liabilityType +
                ", paymentMethod=" + paymentMethod +
                ", amount=" + amount +
                ", narration=" + narration +
                ", createdBy=" + createdBy +
                '}';
    }
}
