package com.hubformath.mathhubservice.model.ops.cashbook;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hubformath.mathhubservice.model.auth.User;
import com.hubformath.mathhubservice.model.sis.Student;
import com.hubformath.mathhubservice.model.systemconfig.PaymentMethod;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "tuition_payments")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class TuitionPayment {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "tuition_payment_id")
    private String tuitionPaymentId;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "cash_transaction_id")
    private CashTransaction cashTransaction;

    @ManyToOne
    @JoinColumn(name = "student_id", unique = false, nullable = false)
    private Student student;

    @ManyToOne
    @JoinColumn(name = "payment_method_id", unique = false, nullable = false)
    private PaymentMethod paymentMethod;

    @Column(name = "payment_date")
    private LocalDate paymentDate;

    @Column(name = "amount")
    private Double amount;

    @OneToOne
    @JoinColumn(name = "invoice_id")
    private Invoice invoice;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "receipt_id")
    private Receipt receipt;

    @Column(name = "narration")
    private String narration;

    @ManyToOne
    @JoinColumn(name = "created_by", unique = false, nullable = false)
    private User createdBy;

    @CreationTimestamp
    @Column(name = "created_at")
    @JsonIgnore
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    @JsonIgnore
    private LocalDateTime updatedAt;

    @SuppressWarnings("unused")
    public TuitionPayment() {
        // Required by JPA
    }

    public TuitionPayment(final CashTransaction cashTransaction,
                          final Student student,
                          final PaymentMethod paymentMethod,
                          final Double amount,
                          final String narration) {
        this.cashTransaction = cashTransaction;
        this.student = student;
        this.paymentMethod = paymentMethod;
        this.paymentDate = LocalDate.now();
        this.amount = amount;
        this.narration = narration;
    }

    public String getTuitionPaymentId() {
        return tuitionPaymentId;
    }

    public void setTuitionPaymentId(String tuitionPaymentId) {
        this.tuitionPaymentId = tuitionPaymentId;
    }

    public CashTransaction getCashTransaction() {
        return cashTransaction;
    }

    public void setCashTransaction(CashTransaction cashTransaction) {
        this.cashTransaction = cashTransaction;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public LocalDate getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(LocalDate paymentDate) {
        this.paymentDate = paymentDate;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Invoice getInvoice() {
        return invoice;
    }

    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public Receipt getReceipt() {
        return receipt;
    }

    public void setReceipt(Receipt receipt) {
        this.receipt = receipt;
    }

    public String getNarration() {
        return narration;
    }

    public void setNarration(String narration) {
        this.narration = narration;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TuitionPayment that)) return false;
        return Objects.equals(getTuitionPaymentId(), that.getTuitionPaymentId())
                && Objects.equals(getCashTransaction(), that.getCashTransaction())
                && Objects.equals(getStudent(), that.getStudent())
                && Objects.equals(getPaymentMethod(), that.getPaymentMethod())
                && Objects.equals(getPaymentDate(), that.getPaymentDate())
                && Objects.equals(getAmount(), that.getAmount())
                && Objects.equals(getInvoice(), that.getInvoice())
                && Objects.equals(getReceipt(), that.getReceipt())
                && Objects.equals(getNarration(), that.getNarration())
                && Objects.equals(getCreatedBy(), that.getCreatedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTuitionPaymentId(),
                            getCashTransaction(),
                            getStudent(),
                            getPaymentMethod(),
                            getPaymentDate(),
                            getAmount(),
                            getInvoice(),
                            getReceipt(),
                            getNarration(),
                            getCreatedBy());
    }

    @Override
    public String toString() {
        return "TuitionPayment{" +
                "tuitionPaymentId=" + tuitionPaymentId +
                ", cashTransaction=" + cashTransaction +
                ", student=" + student +
                ", paymentMethod=" + paymentMethod +
                ", paymentDate=" + paymentDate +
                ", amount=" + amount +
                ", invoiceNumber='" + invoice +
                ", receipt=" + receipt +
                ", narration='" + narration + '\'' +
                ", createdBy=" + createdBy +
                ", createdAt=" + createdAt +
                '}';
    }
}