package com.hubformath.mathhubservice.model.sis;

import com.hubformath.mathhubservice.model.ops.cashbook.PaymentStatus;
import com.hubformath.mathhubservice.model.systemconfig.Subject;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.ReadOnlyProperty;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "classes")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class EnrolledClass {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @ManyToOne
    @JoinColumn(name = "subject_id", unique = false, nullable = false)
    private Subject subject;

    @Column(name = "occurrence")
    private int occurrence;

    @Column(name = "start_date")
    private LocalDate startDate;

    @Column(name = "cost")
    private Double cost;

    @Column(name = "duration")
    private int duration;

    @Enumerated(EnumType.STRING)
    @Column(name = "period")
    private LessonPeriod period;

    @Column(name = "end_date")
    private LocalDate endDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "session_type")
    private SessionType sessionType;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status")
    private PaymentStatus paymentStatus;

    @CreationTimestamp
    @ReadOnlyProperty
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @SuppressWarnings("unused")
    public EnrolledClass() {
        // Used for hibernate instantiation
    }

    public EnrolledClass(Subject subject,
                         int occurrence,
                         LocalDate startDate,
                         Double cost,
                         int duration,
                         LessonPeriod period,
                         LocalDate endDate,
                         SessionType sessionType) {
        this.subject = subject;
        this.occurrence = occurrence;
        this.startDate = startDate;
        this.cost = cost;
        this.duration = duration;
        this.endDate = endDate;
        this.period = period;
        this.sessionType = sessionType;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public int getOccurrence() {
        return occurrence;
    }

    public void setOccurrence(int occurrence) {
        this.occurrence = occurrence;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public Double getCost() {
        return cost;
    }

    public void setCost(Double cost) {
        this.cost = cost;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public LessonPeriod getPeriod() {
        return period;
    }

    public void setPeriod(LessonPeriod period) {
        this.period = period;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public SessionType getSessionType() {
        return sessionType;
    }

    public void setSessionType(SessionType sessionType) {
        this.sessionType = sessionType;
    }

    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof EnrolledClass enrolledClass))
            return false;
        return Objects.equals(this.id, enrolledClass.id) && Objects.equals(this.occurrence, enrolledClass.occurrence)
                && Objects.equals(this.startDate, enrolledClass.startDate)
                && Objects.equals(this.cost, enrolledClass.cost)
                && Objects.equals(this.duration, enrolledClass.duration)
                && Objects.equals(this.period, enrolledClass.period)
                && Objects.equals(this.endDate, enrolledClass.endDate)
                && Objects.equals(this.sessionType, enrolledClass.sessionType)
                && Objects.equals(this.paymentStatus, enrolledClass.paymentStatus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.occurrence,
                this.startDate,
                this.cost,
                this.duration,
                this.sessionType,
                this.paymentStatus,
                this.period,
                this.endDate);
    }

    @Override
    public String toString() {
        return "Class{" +
                "id='" + id + '\'' +
                ", subject=" + subject +
                ", occurrence=" + occurrence +
                ", startDate=" + startDate +
                ", cost=" + cost +
                ", duration=" + duration +
                ", period=" + period +
                ", endDate=" + endDate +
                ", sessionType=" + sessionType +
                ", paymentStatus=" + paymentStatus +
                '}';
    }
}