package com.hubformath.mathhubservice.model.sis;

import com.hubformath.mathhubservice.model.ops.cashbook.PaymentStatus;
import com.hubformath.mathhubservice.model.systemconfig.Subject;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.ReadOnlyProperty;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;

@Entity
@Table(name = "lessons")
@SuppressWarnings("DefaultAnnotationParam") // Columns generated by @JoinColumn are unique by default
public class Lesson {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "lesson_id")
    private String lessonId;

    @ManyToOne
    @JoinColumn(name = "subject_id", unique = false, nullable = false)
    private Subject subject;

    @Column(name = "occurrence")
    private int occurrence;

    @Column(name = "lesson_start_date")
    private LocalDate lessonStartDate;

    @Column(name = "lesson_rate_amount")
    private Double lessonRateAmount;

    @Column(name = "lesson_duration")
    private int lessonDuration;

    @Enumerated(EnumType.STRING)
    @Column(name = "lesson_period")
    private LessonPeriod lessonPeriod;

    @Enumerated(EnumType.STRING)
    @Column(name = "session_type")
    private SessionType sessionType;

    @Enumerated(EnumType.STRING)
    @Column(name = "lesson_payment_status")
    private PaymentStatus lessonPaymentStatus;

    @CreationTimestamp
    @ReadOnlyProperty
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    public Lesson() {
        // Used for hibernate instantiation
    }

    public Lesson(Subject subject,
                  int occurrence,
                  LocalDate lessonStartDate,
                  Double lessonRateAmount,
                  int lessonDuration,
                  LessonPeriod lessonPeriod,
                  SessionType sessionType) {
        this.subject = subject;
        this.occurrence = occurrence;
        this.lessonStartDate = lessonStartDate;
        this.lessonRateAmount = lessonRateAmount;
        this.lessonDuration = lessonDuration;
        this.lessonPeriod = lessonPeriod;
        this.sessionType = sessionType;
    }

    public String getLessonId() {
        return lessonId;
    }

    public void setLessonId(String lessonId) {
        this.lessonId = lessonId;
    }

    public Subject getSubject() {
        return subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    public int getOccurrence() {
        return occurrence;
    }

    public void setOccurrence(int occurrence) {
        this.occurrence = occurrence;
    }

    public LocalDate getLessonStartDate() {
        return lessonStartDate;
    }

    public void setLessonStartDate(LocalDate lessonStartDate) {
        this.lessonStartDate = lessonStartDate;
    }

    public Double getLessonRateAmount() {
        return lessonRateAmount;
    }

    public void setLessonRateAmount(Double lessonRateAmount) {
        this.lessonRateAmount = lessonRateAmount;
    }

    public int getLessonDuration() {
        return lessonDuration;
    }

    public void setLessonDuration(int lessonDuration) {
        this.lessonDuration = lessonDuration;
    }

    public LessonPeriod getLessonPeriod() {
        return lessonPeriod;
    }

    public void setLessonPeriod(LessonPeriod lessonPeriod) {
        this.lessonPeriod = lessonPeriod;
    }

    public SessionType getSessionType() {
        return sessionType;
    }

    public void setSessionType(SessionType sessionType) {
        this.sessionType = sessionType;
    }

    public PaymentStatus getLessonPaymentStatus() {
        return lessonPaymentStatus;
    }

    public void setLessonPaymentStatus(PaymentStatus lessonPaymentStatus) {
        this.lessonPaymentStatus = lessonPaymentStatus;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (!(o instanceof Lesson lesson))
            return false;
        return Objects.equals(this.lessonId, lesson.lessonId) && Objects.equals(this.occurrence, lesson.occurrence)
                && Objects.equals(this.lessonStartDate, lesson.lessonStartDate)
                && Objects.equals(this.lessonRateAmount, lesson.lessonRateAmount)
                && Objects.equals(this.lessonDuration, lesson.lessonDuration)
                && Objects.equals(this.lessonPeriod, lesson.lessonPeriod)
                && Objects.equals(this.sessionType, lesson.sessionType)
                && Objects.equals(this.lessonPaymentStatus, lesson.lessonPaymentStatus);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                this.lessonId,
                this.occurrence,
                this.lessonStartDate,
                this.lessonRateAmount,
                this.lessonDuration,
                this.sessionType,
                this.lessonPaymentStatus,
                this.lessonPeriod);
    }

    @Override
    public String toString() {
        return "Lesson{" +
                "id=" + lessonId +
                ", subject=" + subject +
                ", occurrence=" + occurrence +
                ", lessonStartDate=" + lessonStartDate +
                ", lessonRate=" + lessonRateAmount +
                ", lessonDuration=" + lessonDuration +
                ", lessonPeriod=" + lessonPeriod +
                ", sessionType=" + sessionType +
                '}';
    }
}